import Head from 'next/head';
import { ReactFileState } from '../views/ReactFileStateB-Zustand';

export default function Home() {
  return (
    <div>
      <Head>
        <title>React File State - Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ReactFileState />
      </div>
    </div>
  );
}
