import Head from 'next/head';
import Link from 'next/link';

const routes = [
  ['/with-zustand'],
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>React File State - Compare App - Zustand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style>{`
      .main {
        padding: 5rem 2rem 4rem;
      }
      .main a {
        color: hsl(200, 100%, 50%);
      }
      .main a:visited {
        color: hsl(175, 100%, 50%);
      }
      .main a:hover {
        color: hsl(190, 100%, 50%);
      }
      `}</style>
      <div className={'main'}>
        <nav>
          <ul>
            {routes.map(([path]) => (
              <li key={path}>
                <Link href={path}>{path}</Link>
              </li>
            ))}
          </ul>
        </nav>
      </div>
    </div>
  );
}
